import asyncio
from app.database import engine, SessionLocal, Base
from app.models import Technique

techniques_data = [
    {
        "id": 1,
        "name": "O-soto-gari",
        "japanese_name": "大外刈",
        "category": "Nage-waza",
        "subcategory": "Ashi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "c-A_nP7mKAc",
        "start_seconds": 5,
        "end_seconds": 15,
        "description": "Major outer reaping throw. Uke's weight is shifted onto their right leg as tori reaps it away from behind.",
        "key_points": [
            "Drive uke's weight onto their heel before reaping",
            "Your reaping leg sweeps through in a large arc, hip height or higher",
            "Kuzushi must be achieved before the reap, pulling uke diagonally backward",
            "Maintain chest-to-chest contact throughout the entry",
            "Finish with your body weight following uke to the mat",
        ],
    },
    {
        "id": 2,
        "name": "O-uchi-gari",
        "japanese_name": "大内刈",
        "category": "Nage-waza",
        "subcategory": "Ashi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "0itJFhV9pDQ",
        "start_seconds": 5, "end_seconds": 30,
        "description": "Major inner reaping throw. Tori steps between uke's legs and reaps the near leg from the inside.",
        "key_points": [
            "Enter with your hips low and do not stand upright during the reap",
            "The reaping leg hooks uke's calf/ankle from the inside",
            "Drive your chest through uke to force them backward",
            "Use your sleeve grip to rotate uke's body as you reap",
            "Combines naturally into seoi-nage or ko-uchi-gari for combination attacks",
        ],
    },
    {
        "id": 3,
        "name": "De-ashi-harai",
        "japanese_name": "出足払",
        "category": "Nage-waza",
        "subcategory": "Ashi-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "4BUUvqxi_Kk",
        "start_seconds": 5,
        "end_seconds": 13,
        "description": "Advancing foot sweep. Tori sweeps uke's advancing foot just as it touches the mat and before weight is transferred.",
        "key_points": [
            "Timing is everything, sweep the foot at the exact moment it lands",
            "The sweep is a flat, circular motion, not a kick upward",
            "Both hands pull in the same direction as the sweep",
            "Your own foot stays close to the mat, do not lift it high",
            "Works best when uke is stepping forward or sideways",
        ],
    },
    {
        "id": 4,
        "name": "Ko-uchi-gari",
        "japanese_name": "小内刈",
        "category": "Nage-waza",
        "subcategory": "Ashi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "3Jb3tZvr9Ng",
        "start_seconds": 5,
        "end_seconds": 18,
        "description": "Minor inner reaping throw. A small, deceptive reap targeting the inside of uke's near ankle.",
        "key_points": [
            "Hook the heel of uke's foot, not the calf",
            "The reap is a small, controlled movement, not a powerful swing",
            "Push uke's upper body backward with your chest/hands simultaneously",
            "Works perfectly as a set-up or combination with o-uchi-gari",
            "Often used to disrupt uke's base before a bigger throw",
        ],
    },
    {
        "id": 5,
        "name": "Okuri-ashi-harai",
        "japanese_name": "送足払",
        "category": "Nage-waza",
        "subcategory": "Ashi-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "nw1ZdRjrdRI",
        "start_seconds": 5,
        "end_seconds": 22,
        "description": "Sliding foot sweep. Tori sweeps both of uke's feet as they step sideways, catching both feet mid-air.",
        "key_points": [
            "Sweep the trailing foot just before it lands after a lateral step",
            "Your sweep targets both ankles simultaneously at their closest point",
            "Hands move horizontally in the direction of uke's travel",
            "Requires precise reading of uke's movement pattern",
            "Most effective in randori when uke moves laterally with large steps",
        ],
    },
    {
        "id": 6,
        "name": "O-goshi",
        "japanese_name": "大腰",
        "category": "Nage-waza",
        "subcategory": "Koshi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "yhu1mfy2vJ4",
        "start_seconds": 4,
        "end_seconds": 16,
        "description": "Major hip throw. Tori wraps an arm around uke's waist, loading uke onto the hip and rotating them over.",
        "key_points": [
            "Turn your feet so both toes point away from uke before loading",
            "Your hip must be lower than uke's hip on entry, so bend your knees",
            "The arm around the waist pulls uke tight against your lower back",
            "Rotate your entire body as one unit, do not pull with arms alone",
            "Keep uke's centre of mass directly over your hip throughout",
        ],
    },
    {
        "id": 7,
        "name": "Harai-goshi",
        "japanese_name": "払腰",
        "category": "Nage-waza",
        "subcategory": "Koshi-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "qTo8HlAAkOo",
        "start_seconds": 4,
        "end_seconds": 15,
        "description": "Sweeping hip throw. Tori enters on the hip and sweeps uke's near thigh with the back of their leg.",
        "key_points": [
            "The sweeping leg is straight and drives through like a pendulum",
            "Entry is the same as o-goshi, with your hip lower than uke's",
            "Contact point is the back of your thigh against the front of uke's thigh",
            "Pull uke's upper body forward and downward as you sweep",
            "The combination of hip load and leg sweep creates the throwing power",
        ],
    },
    {
        "id": 8, "name": "Uchi-mata",
        "japanese_name": "内股",
        "category": "Nage-waza",
        "subcategory": "Koshi-waza",
        "difficulty": "advanced",
        "youtube_video_id": "iUpSu5J-bgw",
        "start_seconds": 4,
        "end_seconds": 16,
        "description": "Inner thigh throw. Tori drives their leg up between uke's thighs from the inside, lifting and rotating.",
        "key_points": [
            "Drive the sweeping leg upward through the centre, not to the side",
            "The tip of your sweeping foot points outward at the top of the sweep",
            "Tori's body forms a T-shape with uke at the moment of execution",
            "Pull uke's sleeve arm down and across your body",
            "The forward kuzushi must be established before the leg sweep",
        ],
    },
    {
        "id": 9,
        "name": "Seoi-nage",
        "japanese_name": "背負投",
        "category": "Nage-waza",
        "subcategory": "Te-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "zIq0xI0ogxk",
        "start_seconds": 4,
        "end_seconds": 12,
        "description": "Shoulder throw. Tori turns in, loading uke across the back and shoulders, then bends forward to project them.",
        "key_points": [
            "The arm under uke's armpit drives upward into the armpit, not across the chest",
            "Your feet must be inside uke's feet on entry",
            "Keep your back straight and bend at the knees, not the waist, on entry",
            "The throw comes from straightening your knees, not from pulling with arms",
            "Uke's body must be loaded high on your back, not at hip level",
        ],
    },
    {
        "id": 10,
        "name": "Ippon-seoi-nage",
        "japanese_name": "一本背負投",
        "category": "Nage-waza",
        "subcategory": "Te-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "FQnOlCxo4oI",
        "start_seconds": 4,
        "end_seconds": 15,
        "description": "One-arm shoulder throw. A variation of seoi-nage where tori controls uke's sleeve arm with both arms.",
        "key_points": [
            "Grip uke's sleeve at the elbow and drive it across your body on entry",
            "The elbow of your throwing arm points upward, not sideways",
            "Your body rotation drives the throw, not just your arms",
            "Entry angle must cut across uke's front, not directly in front",
            "Dropping to one knee is a valid variation for shorter tori",
        ],
    },
    {
        "id": 11,
        "name": "Tai-otoshi",
        "japanese_name": "体落",
        "category": "Nage-waza",
        "subcategory": "Te-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "4x6S3Q-Ktv8",
        "start_seconds": 4,
        "end_seconds": 14,
        "description": "Body drop. Tori places their leg as a barrier across uke's lower legs and rotates them over it.",
        "key_points": [
            "Your blocking leg is placed outside uke's near leg and does not sweep",
            "The throw is driven entirely by the hands and rotation of your body",
            "Your blocking foot should be near uke's feet, toes pointing outward",
            "Drive uke's head down and forward over your blocking leg",
            "Common mistake: bending the blocking leg, keep it straight",
        ],
    },
    {
        "id": 12,
        "name": "Tomoe-nage",
        "japanese_name": "巴投",
        "category": "Nage-waza",
        "subcategory": "Sutemi-waza",
        "difficulty": "advanced",
        "youtube_video_id": "880WbHvHv6A",
        "start_seconds": 5,
        "end_seconds": 16,
        "description": "Circle throw. Tori falls backward, places their foot on uke's hip, and uses leg extension to project uke overhead.",
        "key_points": [
            "Plant your foot in uke's lower abdomen/hip region, not the stomach",
            "Pull uke directly downward toward you before extending the leg",
            "Both hands pull strongly as you fall, do not release the grip",
            "The throw is circular, with uke going over your head, not to the side",
            "Your back must hit the mat before the leg extends",
        ],
    },
    {
        "id": 13,
        "name": "Sumi-gaeshi",
        "japanese_name": "隅返",
        "category": "Nage-waza",
        "subcategory": "Sutemi-waza",
        "difficulty": "advanced",
        "youtube_video_id": "5VhduA5xkbA",
        "start_seconds": 5,
        "end_seconds": 21,
        "description": "Corner throw. Tori hooks uke's inner thigh with their foot and uses a backward rolling motion to throw.",
        "key_points": [
            "The hooking foot goes inside uke's near thigh, not around the outside",
            "Your body curls backward, not straight back",
            "Maintain sleeve and lapel grip throughout, as they drive the throw",
            "The movement is compact and close, not stretched out",
            "Often used as a counter to forward-pressing opponents",
        ],
    },
    {
        "id": 14,
        "name": "Kesa-gatame",
        "japanese_name": "袈裟固",
        "category": "Ne-waza",
        "subcategory": "Osaekomi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "NDaQuJOFBYk",
        "start_seconds": 5,
        "end_seconds": 30,
        "description": "Scarf hold. Tori sits beside uke, wrapping one arm around their neck and the other controlling the near arm.",
        "key_points": [
            "Sit on your hip, not on uke's chest, with your weight low and to the side",
            "Control uke's near arm by clamping it tightly against your body",
            "Your head stays low, do not look up",
            "Spread your legs wide for a stable base",
            "Drive your weight into uke's shoulder and neck area, not their chest",
        ],
    },
    {
        "id": 15,
        "name": "Yoko-shiho-gatame",
        "japanese_name": "横四方固",
        "category": "Ne-waza",
        "subcategory": "Osaekomi-waza",
        "difficulty": "beginner",
        "youtube_video_id": "TT7XJVSEQxA",
        "start_seconds": 5,
        "end_seconds": 31,
        "description": "Side four-corner hold. Tori pins uke from the side, controlling the head, near arm, and far leg.",
        "key_points": [
            "One hand reaches under uke's neck, the other between their legs to grip the belt",
            "Your chest is directly on uke's chest",
            "Keep your hips low and legs spread, do not kneel upright",
            "To prevent a bridge-and-roll escape, post your knee against uke's hip",
            "Maintain control of uke's near arm with your elbow/body weight",
        ],
    },
    {
        "id": 16,
        "name": "Tate-shiho-gatame",
        "japanese_name": "縦四方固",
        "category": "Ne-waza",
        "subcategory": "Osaekomi-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "55-rFmBx53g",
        "start_seconds": 5,
        "end_seconds": 24,
        "description": "Vertical four-corner hold. Tori mounts uke in a chest-to-chest position, controlling both arms.",
        "key_points": [
            "Trap uke's arms under your armpits, not just across their chest",
            "Hook your feet under uke's thighs, as this prevents shrimping out",
            "Keep your head down against uke's head to prevent neck bridges",
            "Your weight should be forward on uke's chest, not sitting on the hips",
            "Transition to armbar or choke if uke exposes their arms",
        ],
    },
    {
        "id": 17,
        "name": "Okuri-eri-jime",
        "japanese_name": "送襟絞",
        "category": "Ne-waza",
        "subcategory": "Shime-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "EiqyoVcIAi8",
        "start_seconds": 5,
        "end_seconds": 31,
        "description": "Sliding lapel choke applied from behind. Tori reaches around uke's neck with one hand to grab the far collar.",
        "key_points": [
            "The choking hand grabs as deep on the collar as possible, with the thumb inside",
            "The second hand pulls the near collar downward to tighten the choke",
            "Your body is chest-to-back with uke, maintain control of their back",
            "Hook your legs around uke's hips for body control",
            "The choke is applied by pulling both hands apart, not squeezing",
        ],
    },
    {
        "id": 18,
        "name": "Ude-garami",
        "japanese_name": "腕緘",
        "category": "Ne-waza",
        "subcategory": "Kansetsu-waza",
        "difficulty": "intermediate",
        "youtube_video_id": "AIlTvZb4RlE",
        "start_seconds": 5,
        "end_seconds": 25,
        "description": "Bent armlock targeting uke's shoulder joint. Tori forms a figure-four grip under uke's bent arm and rotates it against the joint.",
        "key_points": [
            "Uke's arm must be bent at roughly 90 degrees at the elbow",
            "Your grip is a figure-four: your hand under uke's arm, gripping your own wrist",
            "The rotation is inward and upward, not just upward",
            "Keep uke's elbow close to your chest throughout",
            "Pressure is on the shoulder joint, apply slowly and with control",
        ],
    },
]


async def seed():
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        async with SessionLocal() as session:
            for data in techniques_data:
                technique = Technique(**data)
                await session.merge(technique)
            await session.commit()
        print(f"Seeded {len(techniques_data)} techniques.")
    except Exception as e:
        print(f"Seed failed: {e}")


if __name__ == "__main__":
    asyncio.run(seed())
